package org.jihye.acnhhb.domain.model

data class Villager(
        val id: String?,
        val name: String,
        val url: String?,
        val altName: String?,
        val titleColor: String?,
        val textColor: String?,
        val imageUrl: String?,
        val species: String,
        val personality: String,
        val gender: String,
        val birthdayMonth: String?,
        val birthdayDay: String?,
        val sign: String?,
        val quote: String?,
        val phrase: String?,
        val clothing: String?,
        val islander: Boolean?,
        val debut: String?,
        val nhDetails: NhDetails?,
)

data class NhDetails(
        val imageUrl: String?,
        val photoUrl: String?,
        val iconUrl: String?,
        val quote: String?,
        val subPersonality: String?,
        val catchphrase: String?,
        val clothing: String?,
        val clothingVariation: String?,
        val favStyles: List<String>,
        val favColors: List<String>,
        val hobby: String?,
        val houseInteriorUrl: String?,
        val houseExteriorUrl: String?,
        val houseWallpaper: String?,
        val houseFlooring: String?,
        val houseMusic: String?,
        val houseMusicNote: String?,
)
